### ISSUE TITLE
[Feat Request] Marketing Material

### ISSUE THREAD

**Issue by dehy** [streams-json/streams.json#2]
Aside the streams themselves, it should be interesting to include some marketing material like a logo in different dimensions : square (mandatory), vertical (if any), horizontal (if any).

Directories often lacks good images or at least recent ones :)

**Comment by ChoiZ** [comment]
Square image is here: https://github.com/streams-json/streams.json/pull/4
I think that having only a square image is enough, the horizontal and vertical bring too much complexity.
